# ==========================================
# Object Repository \u2014 SauceDemo Locators
# ==========================================

# Login Page
login.username = id:user-name
login.password = id:password
login.button = id:login-button
login.error = css:[data-test='error']

# Products Page
products.title = className:title
products.sort = className:product_sort_container
products.items = className:inventory_item_name
products.first.item = xpath:(//div[@class='inventory_item_name'])[1]
products.add.to.cart = css:.btn_inventory

# Cart Page
cart.badge = className:shopping_cart_badge
cart.item = className:cart_item
cart.checkout = id:checkout